version: '3'
services:
  spring-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
  database:
    image: "alpine/h2:latest"
    ports:
      - "1521:1521" # Expose H2 console
    environment:
      - H2_OPTIONS=-ifNotExists
